{% set name = "pytest-remotedata" %}
{% set version = "0.4.1" %}
{% set git_url = "https://github.com/astropy/pytest-remotedata" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05c08bf638cdd1ed66eb01738a1647c3c714737c3ec3abe009d2c1f793b4bb59

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest >=4.6
    - setuptools_scm
  run:
    - python >=3.7
    - pytest >=4.6
    - packaging

test:
  imports:
    - pytest_remotedata

about:
  home: {{ git_url }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Pytest plugin for controlling remote data access
  description: |
    This package provides a plugin for the pytest framework that allows
    developers to control unit tests that require access to data from the
    internet.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
