{% set name = "pytest-remotedata" %}
{% set version = "0.4.2" %}
{% set git_url = "https://github.com/astropy/pytest-remotedata" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ad3eaa2691feecc2071890764d30e06211547577f965e2e4424435c5d887278d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest >=4.6
    - setuptools_scm
  run:
    - python >=3.7
    - pytest >=4.6
    - packaging

test:
  imports:
    - pytest_remotedata

about:
  home: {{ git_url }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Pytest plugin for controlling remote data access
  description: |
    This package provides a plugin for the pytest framework that allows
    developers to control unit tests that require access to data from the
    internet.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
